import Head from "next/head";
import Image from "next/image";
import MainRemain from "../components/MainRemain";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SeemyFont</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <MainRemain />
    </div>
  );
}
