import Head from "next/head";
import MainRemain from "../components/Block/MainRemain";
import React from "react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SeemyFont</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://seemyfont.netlify.app/favicon.ico" />
      </Head>

      <MainRemain />
    </div>
  );
}
